### ISSUE TITLE
how to eval in context of caller's caller 

### ISSUE THREAD

**Issue by JeffreySarnoff** [bramtayl/LazyContext.jl#2]
> Evaluate expressions in the context of their calling environment

How would one evaluate expressions in the context of their caller's calling environment?
How would one evaluate expressions in the context of their caller's caller's calling environment?
How would one dispatch (say over one of two Val types) and allow that dispatch to determine the evaluation context (caller, calller's caller, caller's caller's caller)?

**Comment by bramtayl** [comment]
I'm not sure. Can you give an example?

**Comment by bramtayl** [comment]
```julia
evaluate_in_current_environment(with_context) = evaluate!(with_context)
evaluate_in_parent_environment(with_context) = 
    WithContext(with_context.expression, with_context.environment[:PARENT]) |> evaluate!

@new_environment
@import_to_environment evaluate_in_current_environment evaluate_in_parent_environment

@evaluate begin
    a = 1
    b = 2
    f = b -> begin 
        a = 3
        @evaluate_in_current_environment a + b
    end
    f(4)
end

@evaluate begin
    a = 1
    b = 2
    f = b -> begin 
        a = 3
        @evaluate_in_parent_environment a + b
    end
    f(4)
end
```

**Comment by JeffreySarnoff** [comment]
ahh, ok -- the environment is not a stack frame

**Comment by bramtayl** [comment]
Hmm, I'm not sure what you mean. Provided an environment has enough parents, you should be able to do:

`environment[:PARENT][:PARENT]`

**Comment by JeffreySarnoff** [comment]
thanks for the assit
